### ISSUE TITLE
craftingpad 21w40a-1.0.6 crashes server on launch

### ISSUE THREAD

**Issue by ClaudiusMinimus** [StrikerRockers-Mods/CraftingStick#2]
I'm working to get my pack ready for the 1.18 launch and when I try to run my pack on my test server craftingpad 21w40a-1.0.6 crashes the server on launch

Minecraft 1.18-rc3
Fabric Loader: 0.12.5
craftingpad 21w40a-1.0.6

[latest.log](https://github.com/StrikerRockers-Mods/CraftingPad/files/7612783/latest.log)

**Comment by gbl** [comment]
As I got a mail about this, I thought you opened the same issue with me; I wanted to tell you to open the issue here please, then noticed you already had.

Unfortunately, your crash log is incomplete - it doesn't show the crash stack trace itself. So StrickerRocker will likely not be able to fix it in case it's an incompatibility with any of the other mods.

**Comment by ClaudiusMinimus** [comment]
There was no crash log, and the issue is intermittent. It looks like you have set the Compatibility level set to JAVA_16, when it should be JAVA_17. I have had the same issue with four other mods in the pack.
